faworite= input("შენი საყვარელი სპორტი: ")
print(faworite)

name = input("please your name: ")
print(name)
surname = input("please your surname: ")
print(surname)
age = input("please your age: ")
print(age)
city = input("please your city: ")
print(city)
hobby = input("pleas your hobby: ")
print(hobby)
input("შენი სახელია:Tazo შენი გვარია:kochadze შენი საცხოვრებელი:Tbilisi შენი ასაკი:9" )
print(input)

age = input("your age: ")
print(age)
height =input(" your height: ")
print(height)
print(9 + 1,30)
print(9 - 1,30)
print(9 * 1,30)
